{
 "title": "Traffic Light",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "select distinct target from request_sets rs where stop > (NOW() - INTERVAL '20 minute');"
   }
  ]
 },
 "panels": [
  {
   "title": "IPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as anomaly\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand prediction = 1 and challenged = 0\ngroup by 1 order by 1"
    },
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as attack\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand challenged = 1 --and (low_rate_attack = 0 or low_rate_attack isnull)\ngroup by 1 order by 1"
    },
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as regular\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand prediction = 0 and challenged = 0\ngroup by 1 order by 1"
    },
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as low_rate_attack\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand low_rate_attack = 1 and challenged = 1\ngroup by 1 order by 1"
    }
   ]
  },
  {
   "title": "Regular",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand prediction = 0 and challenged = 0\n"
    }
   ]
  },
  {
   "title": "Anomaly",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE \n$__timeFilter(stop) \nand target = '$Host' \nand prediction = 1 and challenged = 0"
    }
   ]
  },
  {
   "title": "Challenge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand challenged = 1 and low_rate_attack = 0\n"
    }
   ]
  },
  {
   "title": "Low Rate Challenge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand low_rate_attack = 1 and challenged = 1\n"
    }
   ]
  },
  {
   "title": "Passed Challenge",
   "type": "stat",
   "description": "The total number of passed challenge IPs",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand challenged = 1 and challenge_passed = 1 "
    }
   ]
  }
 ]
}